### ISSUE TITLE
sample-lanterna-java : exception on terminal size

### ISSUE THREAD

**Issue by shoon** [griffon/griffon#103]
Remoting into an Ubuntu 14.04 machine with bash shell and byobu (screen) and running the lanterna sample is not able to get the terminal size:

```
[2015-09-11 09:55:48,276] [main] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
java.io.IOException: Timeout while waiting for terminal size report! Maybe your terminal doesn't support cursor position report, please consider using a custom size querier
        at com.googlecode.lanterna.terminal.InputEnabledAbstractTerminal.waitForTerminalSizeReport(InputEnabledAbstractTerminal.java:79)
        at com.googlecode.lanterna.terminal.text.ANSITerminal.getTerminalSize(ANSITerminal.java:62)
        at com.googlecode.lanterna.terminal.text.UnixTerminal.getTerminalSize(UnixTerminal.java:159)
        at com.googlecode.lanterna.screen.Screen.startScreen(Screen.java:203)
        at griffon.lanterna.LanternaGriffonApplication.initialize(LanternaGriffonApplication.java:47)
        at org.example.Launcher.main(Launcher.java:7)
```

Possible solution is to use private mode prior to requesting the size:
```
        terminal.enterPrivateMode();
        TerminalSize terminalSize = terminal.getTerminalSize();
        terminal.exitPrivateMode();
```

Older discussion here:
https://code.google.com/p/lanterna/issues/detail?id=61

Steps to recreate

```
lazybones create griffon-lanterna-java sample-lanterna-java
  (select defaults)
cd sample-lanterna-java/
gradle build
gradle run
```

**Comment by shoon** [comment]
This worked just fine on a windows machine so probably something to do with the remote session, will keep looking
