### ISSUE TITLE
@EventPublisher AST transformation conflicts with application.eventRouter.addEventListener()

### ISSUE THREAD

**Issue by dabolichin** [griffon/griffon#104]
When using @EventPublisher same controller cannot be event listener:
```
@ArtifactProviderFor(GriffonController)
@EventPublisher
class SectionsController {
    SectionsModel model
    SectionsView view

    void mvcGroupInit(Map<String, Object> args) {
        application.eventRouter.addEventListener([
                Foo: { println 'Foo' } as RunnableWithArgs
        ])
    }

    void foo() {
        publishEvent('Foo')
    }
}

```

when instantiating this controller following exception is thrown:

```
griffon.exceptions.InstanceMethodInvocationException: An error occurred while invoking instance method org.sample.MainController.sections()
	at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3034)
Caused by: griffon.exceptions.InstanceNotFoundException: Could not find an instance of type org.sample.SectionsController
	at org.sample.MainController.sections(MainController.groovy:46)
	at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:388)
	at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:339)
	at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3030)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting method, java.lang.NullPointerException: Cannot invoke method setEventRouter() on null object
  at org.sample.SectionsController.setEventRouter(SectionsController.groovy:20)
  while locating org.sample.SectionsController

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke method setEventRouter() on null object
	at org.sample.SectionsController.setEventRouter(SectionsController.groovy)
	at com.google.inject.internal.SingleMethodInjector$2.invoke(SingleMethodInjector.java:72)
	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:91)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 5 more
```

Looks like transformation tries to inject _eventRouter_ before actual controller instance is present.
Removing transformation and using traditional _application.eventRouter.publishEvent()_ solves issue.

**Comment by aalmiray** [comment]
The correct even listener registration for the custom `EventPublisher` would be

    void mvcGroupInit(Map<String, Object> args) {
        addEventListener([
            Foo: { println 'Foo' } as RunnableWithArgs
        ])
    }
