### ISSUE TITLE
ArtifactManager should create View instances inside the UI thread

### ISSUE THREAD

**Issue by aalmiray** [griffon/griffon#110]
View instances are obtained form the application's injector in the currently executing thread, instead of the UI thread

    griffon.exceptions.InstanceMethodInvocationException: An error occurred while invoking instance method com.acme.TasksController.edit()
        at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3034)
        at org.codehaus.griffon.runtime.core.controller.AbstractActionManager.doInvokeAction(AbstractActionManager.java:338)
        at org.codehaus.griffon.runtime.core.controller.AbstractActionManager$1.run(AbstractActionManager.java:257)
        at org.codehaus.griffon.runtime.core.threading.AbstractUIThreadManager$1.run(AbstractUIThreadManager.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: griffon.exceptions.InstanceNotFoundException: Could not find an instance of type com.acme.CreateTaskTemplateView
        at org.codehaus.griffon.runtime.injection.GuiceInjector.getInstance(GuiceInjector.java:153)
        at org.codehaus.griffon.runtime.core.artifact.AbstractArtifactManager.newInstance(AbstractArtifactManager.java:115)
        at org.codehaus.griffon.runtime.core.artifact.AbstractArtifactManager.newInstance(AbstractArtifactManager.java:104)
        at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager.instantiateMembers(DefaultMVCGroupManager.java:234)
        at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager.createMVCGroup(DefaultMVCGroupManager.java:116)
        at org.codehaus.griffon.runtime.core.mvc.AbstractMVCGroupManager.createMVCGroup(AbstractMVCGroupManager.java:324)
        at org.codehaus.griffon.runtime.core.mvc.AbstractMVCHandler.createMVCGroup(AbstractMVCHandler.java:70)
        at org.codehaus.griffon.runtime.core.mractMVCGroup.createMVCGroup(AbstractMVCGroup.java:197)
        at org.codehaus.griffon.runtime.core.artifact.AbstractGriffonMvcArtifact.createMVCGroup(AbstractGriffonMvcArtifact.java:98)
        at com.acme.TasksController.edit(TasksController.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:388)
        at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:339)
        at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3030)
        ... 8 more
    Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

    1) Error injecting constructor, java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-2-thread-4
      at com.acme.CreateTaskTemplateView.<init>(CreateTaskTemplateView.java:39)
      while locating com.acme.CreateTaskTemplateView

    1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at org.codehaus.griffon.runtime.injection.GuiceInjector.getInstance(GuiceInjector.java:151)
        ... 24 more
    Caused by: java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-2-thread-4
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:229)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
        at javafx.stage.Stage.<init>(Stage.java:241)
        at javafx.stage.Stage.<init>(Stage.java:227)
        at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
        at javafx.scene.contlog.<init>(Dialog.java:263)
        at com.acme.CreateTaskTemplateView.<init>(CreateTaskTemplateView.java:57)
        at com.acme.CreateTaskTemplateView$$FastClassByGuice$$dcbc3afd.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        ... 26 more

**Comment by shnplr** [comment]
Assuming view artifacts mvcGroupInit() lifecycle method is always called on the UI thread:

1. Is this also true for view artifacts mvcGroupDestroy() lifecycle method?

2. Also PostConstruct/PreDestroy lifecycle - I'm not 100 % sure if these are "supported" within view artifacts - if so are they always called on the UI thread too?

**Comment by aalmiray** [comment]
`mvcGroupDestroy()` of `view` artifacts is now guaranteed to be invoked inside the UI thread. `@PostConstruct` is already executed inside the UI thread for this type of artifacts.
