### ISSUE TITLE
MessageSource: ExpandableResourceBundle fails handling 'hierarchical' message keys

### ISSUE THREAD

**Issue by fuschl** [griffon/griffon#22]
Griffon application (v. 2.0.0.RC2) fails to start if the message.properties contains 'hierarchical' keys:

medium.concert.venue = Location
medium.concert.venue.name = Name

If I leave out the medium.concert.venue key, everything is fine.

Stacktrace:
    2014-09-21 15:10:46,297 ERROR [JavaFX Application Thread] - [griffon.core.GriffonExceptionHandler] - Uncaught Exception
    java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at griffon.util.ExpandableResourceBundle.processKey(ExpandableResourceBundle.java:57) ~[griffon-core-2.0.0.RC2.jar:2.0.0.RC2]
        at griffon.util.ExpandableResourceBundle.processKey(ExpandableResourceBundle.java:62) ~[griffon-core-2.0.0.RC2.jar:2.0.0.RC2]
        at griffon.util.ExpandableResourceBundle.processKey(ExpandableResourceBundle.java:62) ~[griffon-core-2.0.0.RC2.jar:2.0.0.RC2]
        at griffon.util.ExpandableResourceBundle.<init>(ExpandableResourceBundle.java:46) ~[griffon-core-2.0.0.RC2.jar:2.0.0.RC2]
        at griffon.util.ExpandableResourceBundle.wrapResourceBundle(ExpandableResourceBundle.java:37) ~[griffon-core-2.0.0.RC2.jar:2.0.0.RC2]
        at griffon.util.CompositeResourceBundle.<init>(CompositeResourceBundle.java:48) ~[griffon-core-2.0.0.RC2.jar:2.0.0.RC2]
        at griffon.util.CompositeResourceBundle.<init>(CompositeResourceBundle.java:40) ~[griffon-core-2.0.0.RC2.jar:2.0.0.RC2]
        at griffon.core.i18n.MessageSource$getMessage.call(Unknown Source) ~[na:na]

I am on Java JDK 8 u5 

Regards,
fuschl

**Comment by MarcoPL** [comment]
Same error persists in Griffon 2.13.0. The properties/resources have to be prefix free to work.

**Comment by aalmiray** [comment]
Yes, this feature has not been implemented yet given that configuration values may be set using different formats (properties, Java source code, Groovy scripts, XML, JSON, YAML).

**Comment by MarcoPL** [comment]
Now, that I know the reason for the exception, it is easy to avoid it. But at first, when the application didn't start anymore, it took me some time to realize (only by debugging) that adding a new property to i18n resources was the cause. Maybe a better exception message can help until the feature is implemented?
