### ISSUE TITLE
griffon-swing-java build fails

### ISSUE THREAD

**Issue by chhex** [griffon/griffon#254]
MacOS Sierra 

java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

gradle -version

------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Mac OS X 10.12.6 x86_64

mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /Users/chhex/.sdkman/candidates/maven/current
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Default locale: de_CH, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

Griffon Version : 2.12.0

lazybones create griffon-swing-java sample
Creating project from template griffon-swing-java (latest) in 'sample'
Define value for 'group' [org.example]: com.chesnb
Define value for 'artifactId' [sample]: 
Define value for 'version' [0.1.0-SNAPSHOT]: 
Define value for 'griffonVersion' [2.12.0]: 
Define value for 'package' [com.chesnb]: 
Define value for 'className' [Sample]: 

gradle build

FAILURE: Build failed with an exception.

* What went wrong:
Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

Stacktrace

* Exception is:
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
        at com.github.cr0.gradle.macAppBundle.MacAppBundlePluginExtension.getJREDirName(MacAppBundlePluginExtension.groovy:169)
        at com.github.cr0.gradle.macAppBundle.MacAppBundlePluginExtension$getJREDirName$0.call(Unknown Source)
        at com.github.cr0.gradle.macAppBundle.MacAppBundlePlugin$_createBundleJR

**Comment by aalmiray** [comment]
Looks like the problem is related to the `macappbundle`tasks. Full stacktrace follows

    $  gw createDmg -S
    Using gradle at '/tmp/foo/gradlew' to run buildfile '/tmp/foo/build.gradle':


    FAILURE: Build failed with an exception.

    * What went wrong:
    Ambiguous method overloading for method java.io.File#<init>.
    Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
            [class java.lang.String]
            [class java.net.URI]

    * Try:
    Run with --info or --debug option to get more log output.

    * Exception is:
    groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
    Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
            [class java.lang.String]
            [class java.net.URI]
            at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:3263)
            at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3216)
            at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3159)
            at groovy.lang.MetaClassImpl.createConstructorSite(MetaClassImpl.java:3452)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:91)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
            at com.github.cr0.gradle.macAppBundle.MacAppBundlePluginExtension.getJREDirName(MacAppBundlePluginExtension.groovy:169)
            at com.github.cr0.gradle.macAppBundle.MacAppBundlePluginExtension$getJREDirName$0.call(Unknown Source)
            at com.github.cr0.gradle.macAppBundle.MacAppBundlePlugin$_createBundleJRETask_closure22.doCall(MacAppBundlePlugin.groovy:166)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
            at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
            at groovy.lang.Closure.call(Closure.java:414)
            at groovy.lang.Closure.call(Closure.java:408)
            at groovy.lang.GString.writeTo(GString.java:175)
            at groovy.lang.GString.toString(GString.java:155)
            at org.gradle.api.internal.file.FileOrUriNotationConverter.convert(FileOrUriNotationConverter.java:85)
            at org.gradle.internal.typeconversion.NotationConverterToNotationParserAdapter.parseNotation(NotationConverterToNotationParserAdapter.java:30)
            at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:47)
            at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:125)
            at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:69)
            at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:86)
            at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:68)
            at org.gradle.api.internal.file.copy.DestinationRootCopySpec.getDestinationDir(DestinationRootCopySpec.java:48)
            at org.gradle.api.internal.file.copy.DestinationRootCopySpec_Decorated.getDestinationDir(Unknown Source)
            at org.gradle.api.tasks.Sync.getDestinationDir(Sync.java:100)
            at org.gradle.api.tasks.Sync_Decorated.getDestinationDir(Unknown Source)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
            at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$4.create(TaskPropertyInfo.java:99)
            at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:217)
            at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:97)
            at org.gradle.api.internal.project.taskfactory.TaskClassValidator$FutureValue.call(TaskClassValidator.java:65)
            at org.gradle.util.GUtil.uncheckedCall(GUtil.java:432)
            at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:125)
            at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:94)
            at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:161)
            at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:111)
            at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:94)
            at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:172)
            at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:55)
            at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
            at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
            at com.google.common.collect.Sets.newHashSet(Sets.java:219)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canonicalizedPaths(DefaultTaskExecutionPlan.java:709)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getOutputPaths(DefaultTaskExecutionPlan.java:785)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.recordTaskStarted(DefaultTaskExecutionPlan.java:815)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2700(DefaultTaskExecutionPlan.java:91)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:601)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:590)
            at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNextTask(DefaultTaskExecutionPlan.java:590)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2300(DefaultTaskExecutionPlan.java:91)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:564)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:545)
            at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:545)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
            at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
            at java.lang.Thread.run(Thread.java:748)

It loos like the value of `jreHome` is not computed correctly. Here's a workaround you can place on `gradle/package.gradle`

    if (macosx) {
        File javaHome = new File(System.properties['java.home'])
        javaHome = javaHome.name == 'jre' ? javaHome.parentFile : javaHome

        macAppBundle {
            jreHome = javaHome.absolutePath
            mainClassName = project.mainClassName
            icon = 'src/media/griffon.icns'
            javaProperties.put('apple.laf.useScreenMenuBar', 'true')
        }
    }
