### ISSUE TITLE
griffon.exceptions.NewInstanceException: Cannot create a new instance of type com.iezview.GriffonJavafxKotlinController

### ISSUE THREAD

**Issue by QingMings** [griffon/griffon#262]
I  use lazybones   create  e template project  'GriffonJavafxKotlin'
，When I started from Launch.kt,An error was encountered,
The following is complete exception information
```java 

[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.12.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2017-09-01T09:14:00.699+0200
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: 22df8e659d5f2b180a92321e1ffcd041365cfda5
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 1.8.0_144 (Oracle Corporation 25.144-b01)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Mac OS X 10.12.6 x86_64
[griffon-pool-1-thread-1] INFO griffon.javafx.JavaFXGriffonApplication - Initializing all startup groups: [griffonJavafxKotlin]
[griffon-pool-1-thread-1] ERROR org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager - Can't create member controller with class com.iezview.GriffonJavafxKotlinController
[griffon-pool-1-thread-1] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception.
griffon.exceptions.NewInstanceException: Cannot create a new instance of type com.iezview.GriffonJavafxKotlinController
	at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager.instantiateMembers(DefaultMVCGroupManager.java:272)
	at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager.createMVCGroup(DefaultMVCGroupManager.java:135)
	at org.codehaus.griffon.runtime.core.mvc.AbstractMVCGroupManager.createMVC(AbstractMVCGroupManager.java:265)
	at org.codehaus.griffon.runtime.core.mvc.AbstractMVCGroupManager.createMVC(AbstractMVCGroupManager.java:383)
	at griffon.javafx.AbstractJavaFXGriffonApplication.startup(AbstractJavaFXGriffonApplication.java:432)
	at griffon.javafx.JavaFXGriffonApplication.lambda$afterStart$0(JavaFXGriffonApplication.java:91)
	at org.codehaus.griffon.runtime.core.threading.AbstractUIThreadManager$1.run(AbstractUIThreadManager.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: griffon.exceptions.MembersInjectionException: An error occurred while injecting members into com.iezview.GriffonJavafxKotlinController@3a000bec
	at org.codehaus.griffon.runtime.injection.GuiceInjector.injectMembers(GuiceInjector.java:255)
	at org.codehaus.griffon.runtime.util.DefaultInstantiator.newInstanceFromClass(DefaultInstantiator.java:63)
	at org.codehaus.griffon.runtime.util.DefaultInstantiator.instantiate(DefaultInstantiator.java:50)
	at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager.instantiateMembers(DefaultMVCGroupManager.java:267)
	... 11 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error notifying InjectionListener org.codehaus.griffon.runtime.injection.GuiceInjectorFactory$1@e75e762 of com.iezview.GriffonJavafxKotlinController.
 Reason: java.lang.NullPointerException
  while locating com.iezview.GriffonJavafxKotlinController

1 error
	at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:486)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:67)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987)
	at org.codehaus.griffon.runtime.injection.GuiceInjector.injectMembers(GuiceInjector.java:253)
	... 14 more
Caused by: java.lang.NullPointerException
	at org.codehaus.griffon.runtime.core.controller.AbstractActionManager.createActions(AbstractActionManager.java:157)
	at org.codehaus.griffon.runtime.core.DefaultApplicationConfigurer$3.run(DefaultApplicationConfigurer.java:249)
	at org.codehaus.griffon.runtime.core.event.AbstractEventRouter.fireEvent(AbstractEventRouter.java:206)
	at org.codehaus.griffon.runtime.core.event.AbstractEventRouter$2.run(AbstractEventRouter.java:475)
	at org.codehaus.griffon.runtime.core.event.AbstractEventRouter.publishEvent(AbstractEventRouter.java:138)
	at org.codehaus.griffon.runtime.injection.GuiceInjectorFactory$1.afterInjection(GuiceInjectorFactory.java:78)
	at org.codehaus.griffon.runtime.injection.GuiceInjectorFactory$1.afterInjection(GuiceInjectorFactory.java:75)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:111)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	... 16 more
```

**Comment by aalmiray** [comment]
This looks to be a problem with KAPT. Either it's not setup correctly or your missing the `@ArtifactProviderFor` annotation on the controller. Creating a sample project with the latest griffon-javafx-kotlin template (1.12.0) yields the correct result. Here's how the JAR file looks like when packed

     unzip -l build/libs/sample-0.1.0-SNAPSHOT.jar 
    Archive:  build/libs/sample-0.1.0-SNAPSHOT.jar
      Length      Date    Time    Name
    ---------  ---------- -----   ----
            0  09-18-2017 10:48   META-INF/
          311  09-18-2017 10:48   META-INF/MANIFEST.MF
         1854  09-18-2017 10:43   Config.class
           43  09-18-2017 10:43   META-INF/sample_main.kotlin_module
            0  09-18-2017 10:43   org/
            0  09-18-2017 10:43   org/example/
         1156  09-18-2017 10:43   org/example/ApplicationEventHandler.class
         1227  09-18-2017 10:43   org/example/ApplicationModule.class
          798  09-18-2017 10:43   org/example/LauncherKt.class
         2035  09-18-2017 10:43   org/example/SampleController.class
         1818  09-18-2017 10:43   org/example/SampleModel.class
         5018  09-18-2017 10:43   org/example/SampleView.class
            0  09-18-2017 10:43   META-INF/griffon/
          166  09-18-2017 10:43   META-INF/griffon/griffon.core.artifact.GriffonController
          161  09-18-2017 10:43   META-INF/griffon/griffon.core.artifact.GriffonModel
          160  09-18-2017 10:43   META-INF/griffon/griffon.core.artifact.GriffonView
            0  09-18-2017 10:43   META-INF/services/
          148  09-18-2017 10:43   META-INF/services/griffon.core.injection.Module
          125  09-18-2017 10:43   application.properties
        13888  09-18-2017 10:43   griffon-icon-128x128.png
         1030  09-18-2017 10:43   griffon-icon-16x16.png
         1922  09-18-2017 10:43   griffon-icon-24x24.png
        31616  09-18-2017 10:43   griffon-icon-256x256.png
         2524  09-18-2017 10:43   griffon-icon-32x32.png
         5172  09-18-2017 10:43   griffon-icon-48x48.png
         5933  09-18-2017 10:43   griffon-icon-64x64.png
        15310  09-18-2017 10:43   griffon.png
            0  09-18-2017 10:43   messages.properties
          680  09-18-2017 10:43   org/example/sample.fxml
            0  09-18-2017 10:43   resources.properties
    ---------                     -------
        93095                     30 files

Notice the additional files under `META-INF/griffon`, these are the special files that tell the Griffon runtime how and where to find artifacts. Now, adding a new MVC group using the `lazybones generate` option requires you to modify `Config.kt` with the new group, for example

    $ lazybones generate artifact::mvcgroup
    Define value for 'package' [org.example]:   
    Define value for 'class' name: foo

in `Config.kt`

        entries.put("mvcGroups", hashMapOf(
                "sample" to hashMapOf(
                        "model" to "org.example.SampleModel",
                        "view" to "org.example.SampleView",
                        "controller" to "org.example.SampleController"
                ),
                "foo" to hashMapOf(
                        "model" to "org.example.FooModel",
                        "view" to "org.example.FooView",
                        "controller" to "org.example.FooController"
                )
        ))

When the project is compiled the metadata files should contain the updated information, such as

    cat build/tmp/kapt3/classes/main/META-INF/griffon/griffon.core.artifact.GriffonController 
    # Generated by org.codehaus.griffon.compile.core.processor.artifact.ArtifactProviderProcessor (2.12.0)
    # Mon, 18 Sep 2017 10:53:52 +0200
    org.example.FooController
    org.example.SampleController

It's worth mentioning that you can skip using KAPT completely, instead creating those metadata files manually. Refer to http://andresalmiray.com/writing-javafx-applications-with-kotlin/ for more information on Griffon and Kotlin.

**Comment by QingMings** [comment]
Just create projects through templates without changing them, I check that all files exist，Packaged as jar, I can start successfully，just run 'laucherkt' through IDEA,This error happened. I don't know why

**Comment by aalmiray** [comment]
This is a known limitation of IDEA, they did not implement KAPT support in previous versions, however I'd expect that problem to be fixed in IDEA 2017.3; if that's not the case then please file a ticket at http://youtrack.jetbrains.com/

**Comment by aalmiray** [comment]
See https://github.com/griffon/griffon/issues/189

**Comment by QingMings** [comment]
Thank you.
