### ISSUE TITLE
MVCGruopInstantiationException

### ISSUE THREAD

**Issue by ovaqlab** [griffon/griffon#273]
I want to route between two view. 
![screenshot from 2017 12 11 22 16 50](https://user-images.githubusercontent.com/33068920/33842686-3d98e240-dec1-11e7-95c2-cb6d70704a8e.png)
 I am using griffon javafx framework and **not using any tab view**. In this project After successfully login by the user, user should redirected to dashboard.
Here I attach **Config** 
 ` .e("mvcGroups", map()
                .e("rmsCore", map()
                    .e("view", "com.rms.RmsCoreView")
                )
                .e("login",map()
                    .e("model","com.rms.LoginModel")
                    .e("view", "com.rms.LoginView")
                    .e("controller","com.rms.LoginController")
                )
                .e("dashboard",map()
                        .e("model","com.rms.DashboardModel")
                        .e("view","com.rms.DashboardView")
                        .e("controller","com.rms.DashboardController")
                )
            ); `

This is my **loginController** 
`try {
            if(loginService.login(model.getUsername(), model.getPassword())){
                try{
                    createMVCGroup("dashboard");

                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }

            }
            else{
                updateLoginMessage("Invalid Credentials");
            }
        } catch (Exception e) {
            updateLoginMessage(e.getMessage());
        }`

**parentView**

`@Override
    public void mvcGroupInit(@Nonnull Map<String, Object> args) {
        createMVCGroup("login");
    }

    @Override
    public void initUI() {
        Stage stage = (Stage) getApplication()
                .createApplicationContainer(Collections.<String, Object>emptyMap());
        stage.setTitle(getApplication().getConfiguration().getAsString("application.title"));
        borderPane = new BorderPane();
        Scene scene = new Scene(borderPane);
        scene.getStylesheets().add("bootstrapfx.css");
        stage.setScene(scene);
        stage.sizeToScene();
        getApplication().getWindowManager().attach("mainWindow", stage);
    }`

**dashboard child view**
` public void initUI() {
        Node node = loadFromFXML();
        model.clickCountProperty().bindBidirectional(clickLabel.textProperty());
        connectActions(node, controller);
        connectMessageSource(node);
        BorderPane borderPane = new BorderPane();
        borderPane.setCenter(node);
        parentView.getBorderPane().setCenter(borderPane);
    }`

After successfully login the griffon javafx shows **griffon.exceptions.MVCGroupInstantiationException** Please help me I am new in griffon. @aalmiray : There is no documentation about routing between two views.

**Comment by aalmiray** [comment]
Could you post the whole stacktrace? It should be displayed on the console. Without it we can't tell what's causing the problem.
Also, which group has the `createMVCGroup("login");`?

**Comment by ovaqlab** [comment]
Here I attach stacktrace
`griffon.exceptions.MVCGroupInstantiationException: 
        at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager$FieldInjectionPoint.apply(DefaultMVCGroupManager.java:382)
        at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager.fillReferencedProperties(DefaultMVCGroupManager.java:482)
        at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager.createMVCGroup(DefaultMVCGroupManager.java:162)
        at org.codehaus.griffon.runtime.core.mvc.AbstractMVCGroupManager.createMVCGroup(AbstractMVCGroupManager.java:329)
        at org.codehaus.griffon.runtime.core.mvc.AbstractMVCHandler.createMVCGroup(AbstractMVCHandler.java:76)
        at org.codehaus.griffon.runtime.core.mvc.AbstractMVCGroup.createMVCGroup(AbstractMVCGroup.java:200)
        at org.codehaus.griffon.runtime.core.artifact.AbstractGriffonMvcArtifact.createMVCGroup(AbstractGriffonMvcArtifact.java:85)
        at com.rms.LoginController.login(LoginController.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:407)
        at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:356)
        at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3192)
        at org.codehaus.griffon.runtime.core.controller.AbstractActionManager.doInvokeAction(AbstractActionManager.java:336)
        at org.codehaus.griffon.runtime.core.controller.AbstractActionManager$1.run(AbstractActionManager.java:260)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:748)
Caused by: griffon.exceptions.FieldException: Cannot set field parentView with value com.rms.LoginView@1f54c1dd on com.rms.DashboardView@7d1fbf34
        at griffon.util.GriffonClassUtils.setField(GriffonClassUtils.java:2997)
        at griffon.util.GriffonClassUtils.setFieldValue(GriffonClassUtils.java:2636)
        at org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager$FieldInjectionPoint.apply(DefaultMVCGroupManager.java:376)
        ... 23 more
Caused by: java.lang.IllegalArgumentException: Can not set com.rms.RmsCoreView field com.rms.DashboardView.parentView to com.rms.LoginView
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
        at java.lang.reflect.Field.set(Field.java:764)
        at griffon.util.GriffonClassUtils.setField(GriffonClassUtils.java:2994)
        ... 25 more

[JavaFX Application Thread] INFO griffon.javafx.JavaFXGriffonApplication - Shutdown is in process
`
login group creates a login page, which has LoginController, LoginModel and LoginView.
Please refer below code

`public class Config extends AbstractMapResourceBundle {
    @Override
    protected void initialize(@Nonnull Map<String, Object> entries) {
        map(entries)
            .e("application", map()
                .e("title", "rms-core")
                .e("startupGroups", asList("rmsCore"))
                .e("autoShutdown", true)
            )
            .e("mvcGroups", map()
                .e("rmsCore", map()
                    .e("view", "com.rms.RmsCoreView")
                )
                .e("login",map()
                    .e("model","com.rms.LoginModel")
                    .e("view", "com.rms.LoginView")
                    .e("controller","com.rms.LoginController")
                )
                .e("dashboard",map()
                        .e("model","com.rms.DashboardModel")
                        .e("view","com.rms.DashboardView")
                        .e("controller","com.rms.DashboardController")
                )
            );
    }
}`

**Comment by aalmiray** [comment]
The stacktrace tells me that `DashboardView` expects its `parentView` to be of type `LoginView` but it's actually of type `RmsCoreView`. This means a component in the `rmsCore` group is currently responsible for instantiating the `dashboard` group. You must change the code so that the `login` group is the one that instantiates the `dashboard` group; something along the lines of

	public class LoginController extends AbstractGriffonController {
	    @ControllerAction
	    public void login() {
	        if (loginService.login(model.getUsername(), model.getPassword())) {
	            MVCGroup group = createMVCGroup("dashboard");
	            // show group.view
	            // hide loginGroup.view
	        }
	    }
	}

Be advised that any code that deals with UI must be run inside the UI thread, thus hiding logiGroup.view must be done inside the UI thread. You could also configure typed MVCGroups to make the code shorter, such as

	public class LoginController extends AbstractGriffonController {
	    @ControllerAction
	    public void login() {
	        if (loginService.login(model.getUsername(), model.getPassword())) {
	            DashBoardMVCGroup group = createMVCGroup(DashBoardMVCGroup.class);
	            // show group.view()
	            // hide loginGroup.view
	        }
	    }
	}

**Comment by aalmiray** [comment]
Here's one way to do it https://github.com/aalmiray/griffon-examples/tree/master/login

**Comment by ovaqlab** [comment]
Thank you so much @aalmiray . Really helpfull

**Comment by aalmiray** [comment]
Can this issue be closed?
