### ISSUE TITLE
Lazybones griffon-javafx-java has problems running on java 9

### ISSUE THREAD

**Issue by wagnerma** [griffon/griffon#275]
I have some problems running the lazybones griffon-javafx-java template on java 9. There seems multiple problems. I have to add --add-modules=ALL-SYSTEM to avoid:

`[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.13.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2017-11-30T18:25:44.233-0600
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: f0c351e6eec4d139ea9ef3097551e2dde86ecefb
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 9.0.1 (Oracle Corporation 9.0.1+11)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Windows 10 10.0 amd64
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/mw/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/eeb69005da379a10071aa4948c48d89250febb07/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in Application init method
[main] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception. Stacktrace was sanitized. Set System property 'griffon.full.stacktrace' to 'true' for full report.
java.lang.RuntimeException: Exception in Application init method
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:111)
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:223)
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:132)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at griffon.javafx.JavaFXGriffonApplication.init(JavaFXGriffonApplication.java:70)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	... 9 more
`
Running the app seems not possible, after adding the parameter I get the next exception:
`WARNING: Using incubator modules: jdk.incubator.httpclient
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.13.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2017-11-30T18:25:44.233-0600
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: f0c351e6eec4d139ea9ef3097551e2dde86ecefb
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 9.0.1 (Oracle Corporation 9.0.1+11)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Windows 10 10.0 amd64
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/mw/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/eeb69005da379a10071aa4948c48d89250febb07/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[griffon-pool-1-thread-1] INFO griffon.javafx.JavaFXGriffonApplication - Initializing all startup groups: [client]
[griffon-pool-1-thread-1] ERROR org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager - Can't create member controller with class de.demo.ClientController
[griffon-pool-1-thread-1] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception. Stacktrace was sanitized. Set System property 'griffon.full.stacktrace' to 'true' for full report.
griffon.exceptions.NewInstanceException: Cannot create a new instance of type de.demo.ClientController
	at griffon.javafx.AbstractJavaFXGriffonApplication.startup(AbstractJavaFXGriffonApplication.java:434)
	at griffon.javafx.JavaFXGriffonApplication.lambda$afterStart$0(JavaFXGriffonApplication.java:93)
Caused by: griffon.exceptions.MembersInjectionException: An error occurred while injecting members into de.demo.ClientController@39f42be8
	... 2 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error notifying InjectionListener org.codehaus.griffon.runtime.injection.GuiceInjectorFactory$1@70102ffe of de.demo.ClientController.
 Reason: java.lang.NullPointerException
  while locating de.demo.ClientController

1 error
	at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:486)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:67)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987)
	... 2 more
Caused by: java.lang.NullPointerException
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:111)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	... 3 more
`

**Comment by aalmiray** [comment]
Griffon 2.13.0 is not yet fully ready for JDK9. As you noted, you may need to set additional parameters to allow an application to be Jigsaw compatible. 

The current set of artifacts do not have a explicit module name; there are a couple of split packages; the usage of JSR-305 may or may not cause trouble depending on your particular setup and needs. These and a few more things need to be updated and will cause binary incompatibilities thus the target for a fully JDK9 compatible release is set to 3.0.0, due out next year. 

All this being said, it may still be possible to run a JavaFX Griffon app with JDK9. Allow me a few more days to investigate the stacktrace. Any additional information you may supply would be great.

**Comment by wagnerma** [comment]
Thx for the fast repsonse. Well, I start a new application, evaluating frameworks. At the moment, it seems it is quite early for a Java 9 application, but I will go this way. A lot of your dependent libraries, like guice or testfx have problems running on Java 9 and its uncleaer when they reach it, testfx needs some internal JDK classes moved around, guice seems dropped by google, now completely community driven. So I will start without a framework, so no hurry.
