### ISSUE TITLE
Griffon with JDK and JavaFX 17

### ISSUE THREAD

**Issue by bytecod3r** [griffon/griffon#316]
Is this anything that can be fixed?
Im using griffon 2.16.0 with JDK 17 and JavaFX 17.

```
WARNING: package javafx.traversal not in javafx.graphics
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.16.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2021-12-16T21:19:29Z
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: f9b7e48613e0ae23acf6d6de2517fc4ae7bce360
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 17.0.2 (Azul Systems, Inc. 17.0.2+8-LTS)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Windows 11 10.0 amd64
[JavaFX-Launcher] ERROR org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - An error occurred while initializing the injector
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3963)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:154)
	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:581)
	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:176)
	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at org.codehaus.griffon.runtime.injection.GuiceInjectorFactory.createModules(GuiceInjectorFactory.java:161)
	at org.codehaus.griffon.runtime.injection.GuiceInjectorFactory.createInjector(GuiceInjectorFactory.java:91)
	at org.codehaus.griffon.runtime.injection.GuiceInjectorFactory.createInjector(GuiceInjectorFactory.java:81)
	at org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper.createInjector(AbstractApplicationBootstrapper.java:172)
	at org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper.bootstrap(AbstractApplicationBootstrapper.java:85)
	at griffon.javafx.JavaFXGriffonApplication.init(JavaFXGriffonApplication.java:69)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:825)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by aalmiray** [comment]
Can you share more details on your POM configuration? I've got a sample application that fails win a different way

```
Jan 22, 2022 12:03:08 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1f6c9484'
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.16.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2021-12-16T21:19:29Z
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: f9b7e48613e0ae23acf6d6de2517fc4ae7bce360
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 17.0.1 (Azul Systems, Inc. 17.0.1+12-LTS)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Mac OS X 11.5 x86_64
[JavaFX-Launcher] ERROR org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - An error occurred while initializing the injector
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
```

**Comment by bytecod3r** [comment]
POM means maven config? If yes I dont use Maven, for build.gradle please see below, if you need something other than this pelase let me know.
```
import java.text.SimpleDateFormat


buildscript {
    dependencies {
        classpath 'org.codehaus.griffon:gradle-griffon-plugin:2.16.0'
        classpath 'net.nemerosa:versioning:2.6.1'
        classpath 'com.google.gradle:osdetector-gradle-plugin:1.6.0'
        classpath 'com.guardsquare:proguard-gradle:7.0.0'
    }
}

plugins {
    id "org.openjfx.javafxplugin" version "0.0.11"
    id "org.beryx.runtime" version "1.11.4"
}

repositories {
    mavenCentral()
    maven {
        url "https://repo.spring.io/release"
    }
    maven {
        url "https://repository.jboss.org/maven2"
    }

    maven { url "https://jitpack.io" }
}

configurations.all {
    resolutionStrategy {
        force 'org.slf4j:slf4j-api:2.0.0-alpha2'
        force 'org.springframework:spring-websocket:5.3.15'
        force 'org.springframework:spring-messaging:5.3.15'
        force 'org.springframework:spring-context:5.3.15'
        force 'org.springframework:spring-core:5.3.15'
        force 'org.springframework:spring-web:5.3.15'
        force 'org.springframework:spring-beans:5.3.15'
        force 'org.springframework:spring-aop:5.3.15'
        force 'org.springframework:spring-expression:5.3.15'
        force 'com.fasterxml.jackson.core:jackson-databind:2.13.1'
        force 'com.fasterxml.jackson.core:jackson-core:2.13.1'
        force 'com.google.code.gson:gson:2.8.9'
        force 'com.google.code.findbugs:jsr305:3.0.2'
        force 'junit:junit:4.13.2'
    }
}


apply plugin: 'org.codehaus.griffon.griffon'
apply plugin: 'net.nemerosa.versioning'
apply plugin: 'com.google.osdetector'


Date buildTimeAndDate = new Date()
ext {
    buildDate = new SimpleDateFormat('yyyy-MM-dd').format(buildTimeAndDate)
    buildTime = new SimpleDateFormat('HH:mm:ss.SSSZ').format(buildTimeAndDate)
    macosx = System.getProperty('os.name').contains('Mac OS')
    platform = osdetector.os != 'osx' ? osdetector.os : 'mac'
    platform = osdetector.os != 'windows' ? osdetector.os : 'win'
}

griffon {
    disableDependencyResolution = false
    includeGroovyDependencies = false
    version = '2.16.0'
    toolkit = 'javafx'
    applicationProperties = [
            'build_date'    : buildDate,
            'build_time'    : buildTime,
            'build_revision': versioning.info.commit,
    ]

}

mainClassName = 'org.test.Launcher'

javafx {
    version = '17.0.2'
    modules = ['javafx.base', 'javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.web', 'javafx.swing']
}


dependencies {
    implementation 'org.jetbrains:annotations:22.0.0'
    implementation project(':testAPI')

    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.13.1'
    implementation 'org.codehaus.griffon.plugins:griffon-preferences-plugin:2.1.0'
    implementation 'org.codehaus.griffon.plugins:griffon-preferences-jackson:2.1.0'

    implementation "org.codehaus.griffon:griffon-guice:2.16.0"
    implementation 'org.codehaus.griffon.plugins:griffon-miglayout-javafx:2.0.0'
    implementation files('libs\\HTMLEditorPro.jar')
    implementation group: 'org.controlsfx', name: 'controlsfx', version: '11.1.0'

    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation group: 'org.fxmisc.richtext', name: 'richtextfx', version: '0.10.7'
    implementation 'com.github.NanoHttpd.nanohttpd:nanohttpd:master-SNAPSHOT'
    implementation group: 'org.kordamp.ikonli', name: 'ikonli-javafx', version: '12.3.0'
    implementation group: 'org.kordamp.ikonli', name: 'ikonli-fontawesome5-pack', version: '12.3.0'
    implementation group: 'org.abego.treelayout', name: 'org.abego.treelayout.core', version: '1.0.3'

    implementation 'com.github.pf4j.pf4j:pf4j:master-SNAPSHOT'

    annotationProcessor 'com.github.pf4j.pf4j:pf4j:master-SNAPSHOT'
    implementation 'com.github.pf4j:pf4j-update:master-SNAPSHOT'

    implementation 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'

    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '2.0.0-alpha2'
    implementation group: 'net.time4j', name: 'time4j-base', version: '5.8'

   // implementation group: 'com.dlsc.preferencesfx', name: 'preferencesfx-core', version: '11.8.0'
    griffon 'org.codehaus.griffon.plugins:griffon-preferences-plugin:2.1.0'
    implementation group: 'joda-time', name: 'joda-time', version: '2.10.13'

    implementation 'com.jfoenix:jfoenix:9.0.10'

    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'
    implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'


    implementation 'com.neovisionaries:nv-websocket-client:2.14'
    implementation group: 'org.springframework', name: 'spring-websocket', version: '5.3.15'
    implementation group: 'org.springframework', name: 'spring-messaging', version: '5.3.15'
    implementation group: 'javax.websocket', name: 'javax.websocket-api', version: '1.1'
    implementation group: 'org.reflections', name: 'reflections', version: '0.10.2'
    implementation group: 'io.projectreactor.tools', name: 'blockhound', version: '1.0.6.RELEASE'
}


ext.os = org.gradle.internal.os.OperatingSystem.current()

run {
    args '-env=development'
}

runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    modules = [
            'java.desktop',
            'java.net.http',
            'java.sql',
            'java.naming',
            'java.compiler',
            'java.scripting',
            'java.logging',
            'java.transaction.xa',
            'java.management',
            'java.xml',
            'java.instrument',
            'java.prefs',
            'jdk.unsupported',
            'jdk.jfr',
            'java.security.jgss',
            'jdk.crypto.ec',
            'jdk.crypto.cryptoki',
    ]

    launcher {
        noConsole = false
    }

    // targetPlatform('linux', 'D:\\Dev\\JDK\\Linux\\')
    targetPlatform('windows', 'D:\\Dev\\JDK\\windows\\')


    jpackage {
        installerOptions = [
                '--description', project.description,
        ]

        installerType = project.findProperty('installerType')
        if (org.gradle.internal.os.OperatingSystem.current().windows) {
            // imageOptions += ['--icon', 'src/main/resources/pdfdecorator/gui/icon.ico']
            installerOptions = ['--win-per-user-install', '--win-dir-chooser', '--win-menu', '--win-shortcut', '--verbose']
            targetPlatformName = "windows"
            installerName = 'Operator'
        } else if (org.gradle.internal.os.OperatingSystem.current().macOsX) {
            // imageOptions += ['--icon', 'src/main/resources/pdfdecorator/gui/icon.icns']
        }
        if (installerType in ['deb', 'rpm']) {
            imageOptions += ['--icon', 'src/main/resources/pdfdecorator/gui/icon_256x256.png']
            installerOptions += [
                    '--linux-menu-group', 'Office',
                    '--linux-shortcut'
            ]
        }
        if (installerType == 'deb') {
            installerOptions += [
                    '--linux-deb-maintainer', ''
            ]
        }
        if (installerType == 'rpm') {
            installerOptions += [
                    '--linux-rpm-license-type', 'GPLv3'
            ]
        }
    }

}

startScripts {
    doLast {
        if (!macosx) unixScript.text = unixScript.text.replaceAll('"(-Xdock:(name|icon)=)([^"]*?)(")', ' ')
        windowsScript.text = windowsScript.text.replaceAll('"(-Xdock:(name|icon)=)([^"]*?)(")', ' ')
    }
}

if (hasProperty('debugRun') && ((project.debugRun as boolean))) {
    run {
        jvmArgs '-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005'
    }
}

run {
    jvmArgs '--add-opens=javafx.controls/javafx.scene.control=ALL-UNNAMED'
    jvmArgs '--add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED'
    jvmArgs '--add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED'
    jvmArgs '--add-opens=javafx.graphics/javafx.traversal=ALL-UNNAMED'
    jvmArgs '--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.base/javafx.beans.property=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.base/com.sun.javafx.binding=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED'
    jvmArgs '--add-exports=javafx.web/com.sun.webkit.dom=ALL-UNNAMED'
}
```

**Comment by bytecod3r** [comment]
Fixed with forcing dependency.

```configurations.all {
    resolutionStrategy {
        failOnVersionConflict()
        preferProjectModules()
      ...
        force 'com.google.inject:guice:5.1.0'
       ...
    }
}```
